"""
Custom wrapper for the Kokoro TTS engine to use the GenericTagger.
"""

import os
import sys
from pathlib import Path
from loguru import logger

# Try to import the required modules
try:
    from fugashi import GenericTagger
    from kokoro import KPipeline
except ImportError:
    logger.error("Failed to import required modules. Please install them with: pip install fugashi[unidic-lite] kokoro")
    sys.exit(1)

class KokoroWrapper:
    """
    Wrapper for the Kokoro TTS engine to use the GenericTagger.
    """

    def __init__(self, voice="jf_alpha", language="ja", device="cpu", repo_id=None, cache_dir="cache"):
        """
        Initialize the Kokoro TTS wrapper.

        Args:
            voice (str): The voice to use.
            language (str): The language to use.
            device (str): The device to use (cpu or cuda).
            repo_id (str): The repository ID for the Kokoro model.
            cache_dir (str): The cache directory for the Kokoro model.
        """
        self.voice = voice
        self.language = language
        self.device = device
        self.repo_id = repo_id
        self.cache_dir = cache_dir

        # Create the tagger with the correct dictionary
        self.tagger = self._create_tagger()

        # Initialize the Kokoro pipeline
        self._initialize_pipeline()

    def _create_tagger(self):
        """
        Create a tagger with the correct dictionary.

        Returns:
            GenericTagger: The tagger instance.
        """
        # Try to find the MeCab dictionary
        mecabrc = "/usr/local/etc/mecabrc"
        if os.path.exists(mecabrc):
            with open(mecabrc, 'r') as f:
                for line in f:
                    if line.startswith('dicdir'):
                        dicdir = line.split('=')[1].strip()
                        logger.info(f"Using MeCab dictionary: {dicdir}")
                        return GenericTagger(f'-d {dicdir}')

        # Fallback to ipadic-utf8
        logger.info("Using fallback MeCab dictionary: /var/lib/mecab/dic/ipadic-utf8")
        return GenericTagger('-d /var/lib/mecab/dic/ipadic-utf8')

    def _initialize_pipeline(self):
        """
        Initialize the Kokoro pipeline.
        """
        try:
            # Import our custom JAG2P class
            try:
                from .custom_jag2p import patch_jag2p
                # Patch the JAG2P class
                patch_jag2p()
            except ImportError:
                logger.warning("custom_jag2p not found. Using default JAG2P.")
            except Exception as e:
                logger.warning(f"Failed to patch JAG2P class: {e}")

            # Convert language code to Kokoro format (e.g., 'ja' to 'j')
            lang_code = self._convert_language_code(self.language)

            # Initialize the Kokoro pipeline
            if self.repo_id:
                self.pipeline = KPipeline(
                    lang_code=lang_code,
                    repo_id=self.repo_id,
                    device=self.device
                )
            else:
                self.pipeline = KPipeline(
                    lang_code=lang_code,
                    device=self.device
                )

            logger.info(f"Initialized Kokoro pipeline with voice: {self.voice}")
        except Exception as e:
            logger.error(f"Failed to initialize Kokoro pipeline: {e}")
            raise

    def _convert_language_code(self, language: str) -> str:
        """
        Convert standard language code to Kokoro format.

        Args:
            language: Standard language code (e.g., 'en', 'ja')

        Returns:
            Kokoro language code ('a' for English, 'j' for Japanese, etc.)
        """
        # Kokoro uses 'a' for English
        if language.lower() in ['en', 'eng', 'english']:
            return 'a'
        # Kokoro uses 'j' for Japanese
        elif language.lower() in ['ja', 'jp', 'jpn', 'japanese']:
            return 'j'
        # For other languages, use the original code
        return language

    def generate(self, text, output_path=None):
        """
        Generate speech from text.

        Args:
            text (str): The text to generate speech from.
            output_path (str): The path to save the generated audio to.

        Returns:
            str: The path to the generated audio file.
        """
        try:
            # Generate speech
            generator = self.pipeline(text, voice=self.voice)

            # Kokoro returns a generator with (gs, ps, audio) tuples
            # We'll use the first generated audio segment
            for _, _, audio in generator:
                # Save the audio to a file
                import soundfile as sf
                sf.write(output_path, audio, 24000)  # Use 24kHz sample rate
                return output_path

            # If no audio was generated, raise an exception
            raise RuntimeError("No audio was generated by the Kokoro pipeline")
        except Exception as e:
            logger.error(f"Failed to generate speech: {e}")
            raise
