name: Waka Readme

on:

  push:
    paths:
      - '.github/workflows/stats.yml'
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: daoch4n/github-waka-stats-ja@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_UPDATED_DATE: "False"
          SHOW_PROFILE_VIEWS: "True"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_COMMIT: "False"
          SHOW_LOC_CHART: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_SHORT_INFO: "True"
          SHOW_TIMEZONE: "True"
          LOCALE: "ja_JP"
